ARG VERSION=v2.5.9-stable

FROM parity/parity:$VERSION

#COPY docker-entrypoint.sh /entrypoint.sh
#COPY bitcoin.conf /bitcoin.conf

#EXPOSE 8332 8333

#ENTRYPOINT ["sh", "/entrypoint.sh"]

#CMD ["bitcoind"]

